= Infinispan Spring-Boot samples

.Covers
* [x] Embedded cache
* [x] Remote cache
* [x] https://docs.spring.io/spring-boot/docs/current/actuator-api/html/[Actuator] cache metrics
* [x] Integration with https://prometheus.io/[Prometheus]

== Building instructions

Invoke `mvn clean install` for the embedded or the remote example

== Running instructions

=== Embedded

`mvn spring:boot run`

=== Remote

Use docker or download and run the http://infinispan.org/download/[Infinispan Server]

[source,bash]
.Docker
----
docker run -it -p 11222:11222 jboss/infinispan-server:9.4.1.Final
----

[source,bash]
.Server
----
cd UNZIP_SERVER_PATH/bin/
./standalone.sh
----

== Display actuator stats

You will see in ```http://localhost:8080/actuator/metrics``` a list of metrics available.
Cache metrics are prefixed by *"cache."*

http://localhost:8080/actuator/metrics

Display each metric for each cache using tags. For example for the 'puts' stats in the basque-names cache:
http://localhost:8080/actuator/metrics/cache.puts?tag=name:basque-names


== Run Prometheus

For docker for mac or windows, execute `run-prometheus.sh`.
The `prometheus.yml` file contains the _host.docker.internal_ binding that will allow prometheus scrap the metrics exposed by spring actuator.

