= Infinispan Spring Boot Starter

Quickly get your Spring Boot project up and running with Infinispan.

== Setting Up Your Project

This starter provides a set of managed transitive dependencies that include everything your Spring Boot project needs to seamlessly interact with Infinispan in one of two modes:

* Embedded Mode runs Infinispan inside your application.
* Remote Client/Server Mode connects your application to an Infinispan cluster.

To set up your project, add one of the following to your `pom.xml` file:

.Embedded Mode
[source,xml,options="nowrap"]
----
<dependency>
    <groupId>org.infinispan</groupId>
    <artifactId>infinispan-spring-boot-starter-embedded</artifactId>
    <version>${version.infinispan.starter}</version>
</dependency>
----

.Remote Client/Server Mode
[source,xml,options="nowrap"]
----
<dependency>
    <groupId>org.infinispan</groupId>
    <artifactId>infinispan-spring-boot-starter-remote</artifactId>
    <version>${version.infinispan.starter}</version>
</dependency>
----

=== Enforcing Infinispan Versions

This starter uses a high-level API to ensure compatibility between major versions of Infinispan. However you can enforce a specific version of Infinispan with the `infinispan-bom` module.

Add `infinispan-bom` to your `pom.xml` file before the starter dependenices, as follows:

[source,xml,options="nowrap"]
----
<dependencyManagement>
    <dependencies>
       <dependency>
           <groupId>org.infinispan</groupId>
           <artifactId>infinispan-bom</artifactId>
           <version>{version.infinispan}</version>
           <type>pom</type>
           <scope>import</scope>
       </dependency>
       <dependency>
           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter-parent</artifactId>
           <version>${version.spring.boot}</version>
           <type>pom</type>
           <scope>import</scope>
       </dependency>
       <dependency>
           <groupId>org.infinispan</groupId>
           <artifactId>infinispan-spring-boot-starter</artifactId>
           <version>${version.infinispan.starter}</version>
       </dependency>
    </dependencies>
 </dependencyManagement>
----

== Running in Embedded Mode

. Add `infinispan-spring-boot-starter-embedded` to your project's classpath to enable Embedded mode.
+
This starter operates in Remote Client/Server mode with `infinispan-spring-boot-starter-remote` on the classpath by default.
+
. Use the Spring `@Autowired` annotation to include an `EmbeddedCacheManager` bean in your Java configuration classes, as in the following example:
+
[source,java,options="nowrap"]
----
private final EmbeddedCacheManager cacheManager;

@Autowired
public YourClassName(EmbeddedCacheManager cacheManager) {
    this.cacheManager = cacheManager;
}
----
+
You are now ready to use Infinispan in Embedded Mode. Here is a simple example:
+
[source,java,options="nowrap"]
----
cacheManager.getCache("testCache").put("testKey", "testValue");
System.out.println("Received value from cache: " + cacheManager.getCache("testCache").get("testKey"));
----

=== Customizing the Cache Manager

Customize the cache manager with the following configuration beans:

* `InfinispanGlobalConfigurer`
* `InfinispanCacheConfigurer`
* `Configuration`
* `InfinispanConfigurationCustomizer`
* `InfinispanGlobalConfigurationCustomizer`
+
[NOTE]
====
You can create one `InfinispanGlobalConfigurer` bean only. However you can create multiple configurations with the other beans.
====

.InfinispanCacheConfigurer Bean
[source,java,options="nowrap"]
----
@Bean
public InfinispanCacheConfigurer cacheConfigurer() {
	return manager -> {
		final Configuration ispnConfig = new ConfigurationBuilder()
                        .clustering()
                        .cacheMode(CacheMode.LOCAL)
                        .build();

		manager.defineConfiguration("local-sync-config", ispnConfig);
	};
}
----

.Configuration Bean
Link the bean name to the cache that it configures, as follows:
[source,java,options="nowrap"]
----
@Bean(name = "small-cache")
public org.infinispan.configuration.cache.Configuration smallCache() {
    return new ConfigurationBuilder()
        .read(baseCache)
        .memory().size(1000L)
        .memory().evictionType(EvictionType.COUNT)
        .build();
}

@Bean(name = "large-cache")
public org.infinispan.configuration.cache.Configuration largeCache() {
    return new ConfigurationBuilder()
        .read(baseCache)
        .memory().size(2000L)
        .build();
}
----

.Customizer Beans
[source,java,options="nowrap"]
----
@Bean
public InfinispanGlobalConfigurationCustomizer globalCustomizer() {
   return builder -> builder.transport().clusterName(CLUSTER_NAME);
}

@Bean
public InfinispanConfigurationCustomizer configurationCustomizer() {
   return builder -> builder.memory().evictionType(EvictionType.COUNT);
}
----

=== Enabling Spring Cache Support

Add the `@EnableCaching` annotation to your application to enable Spring Cache support.

When the Infinispan Spring Boot Starter detects the `EmbeddedCacheManager` bean, it instantiates a new `SpringEmbeddedCacheManager`, which provides an implementation of
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html[Spring Cache].

=== Configuration Properties

Include the following properties in the `application.properties` or `application.yml` file to configure your project:

[source,yaml,options="nowrap"]
----
infinispan.embedded.enabled = # Enables Infinispan capabilities in your application. The value is true (default) or false.
infinispan.embedded.machineId = # Sets the Spring state machine ID.
infinispan.embedded.clusterName = # Sets the name of the Infinispan cluster.
infinispan.embedded.configXml = # Specifies an Infinispan XML configuration file.
----

[NOTE]
====
If you specify an Infinispan configuration with the `infinispan.embedded.configXml` property, it takes priority over the global configuration bean or any configuration customizer.
====

== Running in Remote Client/Server Mode

. Provide the location for the Infinispan server so the starter can create the `RemoteCacheManager` bean.
+
This starter first attempts to locate the server from the `hotrod-client.properties` file on the classpath. If not found, the starter then attempts to locate the server from your `application.properties` file.
+
* `hotrod-client.properties`:
+
[source,text,options=nowrap]
----
infinispan.client.hotrod.server_list=127.0.0.1:6667
----
+
* `application.properties`:
+
[source,text,options=nowrap]
----
infinispan.remote.server-list=127.0.0.1:11222
----
+
. Use the Spring `@Autowired` annotation to include your own custom cache manager class in your application:
+
[source,java,options="nowrap"]
----
private final RemoteCacheManager cacheManager;

@Autowired
public YourClassName(RemoteCacheManager cacheManager) {
    this.cacheManager = cacheManager;
}
----

=== Customizing the Cache Manager

Customize the cache manager with the following configuration beans:

* `InfinispanRemoteConfigurer`
* `Configuration`
* `InfinispanRemoteCacheCustomizer`
+
[NOTE]
====
You can create one `InfinispanRemoteConfigurer` bean only. However you can create multiple configurations with the other beans.
====

.InfinispanRemoteConfigurer Bean
[source,java,options="nowrap"]
----
@Bean
public InfinispanRemoteConfigurer infinispanRemoteConfigurer() {
    return () -> new ConfigurationBuilder()
        .addServer()
        .host("127.0.0.1")
        .port(12345)
        .build();
}
----

.Configuration Bean
[source,java,options="nowrap"]
----
@Bean
public org.infinispan.client.hotrod.configuration.Configuration customConfiguration() {
    new ConfigurationBuilder()
        .addServer()
        .host("127.0.0.1")
        .port(12345)
        .build();
}
----

.InfinispanRemoteCacheCustomizer Bean
[source,java,options="nowrap"]
----
@Bean
public InfinispanRemoteCacheCustomizer customizer() {
    return b -> b.tcpKeepAlive(false);
}
----

[TIP]
====
Use the `@Ordered` annotation to apply customizers in a specific order.
====

=== Enabling Spring Cache Support

Add the `@EnableCaching` annotation to your application to enable Spring Cache support.

When the Infinispan Spring Boot Starter detects the `RemoteCacheManager` bean, it instantiates a new `SpringRemoteCacheManager`, which provides an implementation of
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html[Spring Cache].

=== Enabling Spring Session Support

http://infinispan.org/docs/stable/user_guide/user_guide.html#externalizing_session_using_spring_session[Infinispan Spring Session support] is built on
`SpringRemoteCacheManager` and `SpringEmbeddedCacheManager`. This starter produces those beans by default.

To use Spring Session in your project, do the following:

. Add this starter to your project.
. Add Spring Session to the classpath.
. Add the following annotations to your configuration:
- `@EnableCaching`
- `@EnableInfinispanRemoteHttpSession`
- `@EnableInfinispanEmbeddedHttpSession`

=== Configuration Properties

Include the following properties in the `application.properties` or `application.yml` file to configure your project:

[source,yaml,options="nowrap"]
----
infinispan.remote.clientProperties = # Specifies a custom filename for Hot Rod client properties.
infinispan.remote.enabled = # Enables Infinispan capabilities in your application. The value is true (default) or false.
infinispan.remote.serverList = # Defines a comma-separated list of Infinispan servers in this format: `host1[:port],host2[:port]`.
infinispan.remote.socketTimeout = # Sets a timeout value, in milliseconds, for socket connections.
infinispan.remote.connectTimeout = # Sets a timeout value for initializing connections with Infinispan servers.
infinispan.remote.maxRetries = # Sets the maximum number of attempts to connect to Infinispan servers.
----

You can also set application parameters covered in the link:http://infinispan.org/docs/stable/user_guide/user_guide.html#configuration_11[Infinispan documentation].

== Spring Boot Tutorials

Now that you have an Infinispan project set up with this Spring Boot Starter, take a look at the https://github.com/infinispan/infinispan-simple-tutorials/tree/master/spring-boot[Infinispan Simple Tutorials for Spring Boot].
